### ISSUE TITLE
Show full toolbar in Dolphin with most common buttons by default

### ISSUE THREAD

**Issue by saudiqbal** [glibg10b/ltt-linux-challenge-issues#33] opened 2021-12-06 21:24 UTC
![Screenshot_20211206_161328](https://user-images.githubusercontent.com/6971514/144924475-f1b31bb5-3e0c-4441-a127-c9d39b51b963.png)

**Comment by glibg10b** [comment] 2021-12-07 06:58
Duplicate of #12

**Closed by glibg10b** 2021-12-07 06:58 UTC
